import { Github, Linkedin, Mail, ExternalLink, ArrowDown } from "lucide-react";
import { ImageWithFallback } from "@/app/components/figma/ImageWithFallback";

export default function PortfolioOne() {
  const projects = [
    {
      title: "HomeVerse (Work in Progress)",
      description: "An AI-powered interior design platform currently under development that transforms room photos into editable 3D spaces. Built with Next.js, FastAPI, Three.js, React Three Fiber, and PostgreSQL.",
      tech: ["Next.js", "Three.js", "FastAPI", "PostgreSQL", "React Three Fiber", "AI"],
      link: "https://github.com/AnishaPaturi/HomeVerse",
    },
    {
      title: "AI CareerOS (CareerPilot-AI)",
      description: "A unified AI-powered career preparation and placement ecosystem bringing together mock interviews, resume auditing, DSA planning, and RAG search. Built using a Spring Boot and FastAPI microservices architecture.",
      tech: ["Spring Boot", "FastAPI", "React", "MySQL", "ChromaDB", "LangChain", "Microservices"],
      link: "https://github.com/AnishaPaturi/CareerPilot-AI",
      liveLink: "https://career-pilot-ai-delta.vercel.app",
    },
    {
      title: "ResumeIQ",
      description: "A multi-agent AI resume analyzer that scans resumes, calculates an ATS compatibility score, performs skill gap analysis against job target criteria, and generates personalized roadmap recommendations.",
      tech: ["React", "TypeScript", "FastAPI", "Python", "MongoDB", "OpenRouter", "AI Agents"],
      link: "https://github.com/AnishaPaturi/ResumeIQ",
    },
    {
      title: "SentinelX",
      description: "A desktop-based network security and vulnerability assessment platform capable of multithreaded port scanning, banner grabbing, host discovery, and real-time packet capture/protocol analysis using Pcap4J.",
      tech: ["Java", "Swing", "Socket Programming", "Pcap4J", "Networking", "Multithreading"],
      link: "https://github.com/AnishaPaturi/SentinelX",
      liveLink: "https://sentinel-x-beta-pink.vercel.app/",
    },
    {
      title: "Secret Santa",
      description: "A real-time web application modernizing the traditional gift exchange with QR code invites and instant assignments. Built with Next.js, React, Firebase, Tailwind CSS, and Framer Motion.",
      tech: ["Next.js", "React", "Firebase", "Tailwind CSS", "Framer Motion"],
      link: "https://github.com/AnishaPaturi/Secret-Santa-",
      liveLink: "https://secret-santa-theta-nine.vercel.app/",
    },
    {
      title: "Mood-Angles",
      description: "An AI-powered mental health and telepsychiatry platform combining intelligent mood tracking, machine learning, RAG, and telepsychiatry services. Built with the MERN stack, Python, and LangChain.",
      tech: ["MongoDB", "Express.js", "React", "Node.js", "Python", "LangChain"],
      link: "https://github.com/AnishaPaturi/Mood-Angles",
      liveLink: "https://mood-angles.vercel.app",
    },
    {
      title: "CodeSleuth – Human vs AI Code Detector",
      description: "An AI-powered developer tool that analyzes source code to determine whether it was written by a human or generated by an AI model. Built with Python and OpenAI's GPT models.",
      tech: ["Python", "OpenAI GPT", "AI", "Code Analysis"],
      link: "https://github.com/AnishaPaturi/AuthenCode",
    },
    {
      title: "AutoDeck",
      description: "A Python automation tool designed to streamline the organization of image collections and automatically generate professional PowerPoint presentations. Built with Python, python-pptx, and Pillow.",
      tech: ["Python", "python-pptx", "Pillow", "Automation"],
      link: "https://github.com/AnishaPaturi/AutoDeck",
    },
    {
      title: "GradeSync",
      description: "A comprehensive student grade management and analytics system showcasing multiple data persistence strategies (flat files, JSON, MySQL) with responsive web dashboards, a Python HTTP server, and PHP modules.",
      tech: ["Python", "PHP", "MySQL", "HTML", "CSS", "JavaScript"],
      link: "https://github.com/AnishaPaturi/GradeSync",
    },
    {
      title: "Just Do It.",
      description: "A modern, responsive to-do list application designed to help users organize daily tasks through a clean interface and engaging animations. Built using HTML, CSS, Bootstrap, and vanilla JavaScript.",
      tech: ["HTML", "CSS", "Bootstrap", "JavaScript"],
      link: "https://github.com/AnishaPaturi/To-Do",
      liveLink: "https://to-do-phi-kohl.vercel.app/",
    },
    {
      title: "Murder Mystery Web Platform (Work in Progress)",
      description: "An interactive web application currently under development where users solve fictional murder cases by exploring crime scenes, analyzing evidence, and connecting clues. Built with React, Vite, Tailwind CSS, and shadcn/ui.",
      tech: ["React", "Vite", "Tailwind CSS", "shadcn/ui"],
      link: "https://github.com/AnishaPaturi/Murder_Mystery_Web_Platform",
    },
    {
      title: "AI Procurement Verification Agent",
      description: "A production-grade, multi-agent AI system that automates the verification of vendor invoices against purchase orders. Built with Python, FastAPI, LangChain, LangGraph, and OpenAI.",
      tech: ["Python", "FastAPI", "LangChain", "LangGraph", "OpenAI"],
      link: "https://github.com/AnishaPaturi/Invoice_Agent",
    },
    {
      title: "CineMatch AI – Movie Recommendation Platform",
      description: "An AI-powered movie recommendation ecosystem combining machine learning with full-stack web and mobile development. Built with React, React Native, FastAPI, Node.js, Express, MongoDB, and Docker.",
      tech: ["React Native", "React", "FastAPI", "Node.js", "MongoDB", "Docker"],
      link: "https://github.com/AnishaPaturi/movie-recommendation-platform",
      liveLink: "https://movie-recommendation-platform-nine.vercel.app/",
    },
  ];

  return (
    <div className="size-full overflow-auto bg-gradient-to-br from-purple-50 via-white to-blue-50">
      {/* Hero Section */}
      <section className="min-h-screen flex flex-col items-center justify-center px-6 relative">
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-white/50 to-white" />
        <div className="relative z-10 max-w-4xl mx-auto text-center">
          <div className="mb-8">
            <div className="inline-block p-1 bg-gradient-to-r from-purple-500 to-blue-500 rounded-full mb-6">
              <div className="bg-white rounded-full p-2">
                <div className="size-32 bg-gradient-to-br from-purple-500 to-blue-500 rounded-full flex items-center justify-center text-white text-5xl">
                  AP
                </div>
              </div>
            </div>
          </div>
          <h1 className="text-6xl mb-4 bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
            Anisha Paturi
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
            Full Stack Developer & Problem Solver
          </p>
          <p className="text-gray-500 mb-12 max-w-xl mx-auto">
            Passionate about creating innovative solutions that make a difference. 
            Experienced in building scalable applications with modern technologies.
          </p>
          <div className="flex items-center justify-center gap-4 mb-12">
            <a
              href="https://github.com/AnishaPaturi"
              target="_blank"
              rel="noopener noreferrer"
              className="p-3 bg-white rounded-full shadow-lg hover:shadow-xl transition-all hover:-translate-y-1"
            >
              <Github className="size-6" />
            </a>
            <a
              href="https://linkedin.com"
              target="_blank"
              rel="noopener noreferrer"
              className="p-3 bg-white rounded-full shadow-lg hover:shadow-xl transition-all hover:-translate-y-1"
            >
              <Linkedin className="size-6" />
            </a>
            <a
              href="mailto:your.email@example.com"
              className="p-3 bg-white rounded-full shadow-lg hover:shadow-xl transition-all hover:-translate-y-1"
            >
              <Mail className="size-6" />
            </a>
          </div>
          <ArrowDown className="size-6 mx-auto animate-bounce text-gray-400" />
        </div>
      </section>

      {/* Projects Section */}
      <section className="py-20 px-6 bg-white">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-4xl mb-4 text-center">Featured Projects</h2>
          <p className="text-center text-gray-600 mb-16 max-w-2xl mx-auto">
            A collection of projects showcasing my skills in web development, 
            mobile applications, and innovative problem-solving
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {projects.map((project, index) => (
              <div
                key={index}
                className="group bg-gradient-to-br from-purple-50 to-blue-50 rounded-2xl p-6 hover:shadow-2xl transition-all duration-300 hover:-translate-y-2"
              >
                <div className="flex items-start justify-between mb-4">
                  <div className="flex flex-wrap items-center gap-2">
                    <h3 className="text-xl font-medium">{project.title}</h3>
                    {project.liveLink && (
                      <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 text-xs rounded-full font-medium">Live</span>
                    )}
                  </div>
                  <a
                    href={project.liveLink || project.link}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="p-2 bg-white rounded-lg opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <ExternalLink className="size-4" />
                  </a>
                </div>
                <p className="text-gray-600 mb-4 text-sm">{project.description}</p>
                <div className="flex flex-wrap gap-2">
                  {project.tech.map((tech, i) => (
                    <span
                      key={i}
                      className="px-3 py-1 bg-white rounded-full text-xs text-gray-700"
                    >
                      {tech}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section className="py-20 px-6 bg-gradient-to-br from-purple-100 to-blue-100">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl mb-4">Let's Work Together</h2>
          <p className="text-gray-600 mb-8">
            I'm always open to discussing new projects, creative ideas, or opportunities to be part of your vision.
          </p>
          <a
            href="mailto:your.email@example.com"
            className="inline-block px-8 py-4 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-full hover:shadow-2xl transition-all hover:-translate-y-1"
          >
            Get In Touch
          </a>
        </div>
      </section>
    </div>
  );
}
